[package]
name = "ec"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = { workspace = true, features = ["nip59"] }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
chrono = "0.4.40"
tracing-subscriber = "0.3.19"
rsa              = "0.9.8"              # Sin la feature `pkcs8` para evitar conflicto
rand             = "0.8"
serde_json = "1.0.140"
